name 'autoupdates-off'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures autoupdates-off'
long_description 'Installs/Configures autoupdates-off'
version '0.1.0'
